### ISSUE TITLE
Support Debian 11

### ISSUE THREAD

**Issue by staticdev** [green-leader/ansible-role-codium#2]
Could you please add it to tests and supported version?

**Comment by green-leader** [comment]
Sure, it'll probably be another 24 hours before I'm at a workstation I can make the changes on though.

Dec 12, 2021 10:36:30 staticdev ***@***.***>:

**Comment by staticdev** [comment]
Thanks a lot @green-leader 
Just an info, to show on Ansible Galaxy (https://galaxy.ansible.com/green_leader/codium) you need to create another release on Github.

**Comment by green-leader** [comment]
Thanks @staticdev for the heads up. I've gone ahead and done so.

**Comment by staticdev** [comment]
Thanks again.
